-- MySQL Script generated by MySQL Workbench
-- Mon Nov 13 13:05:43 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wololo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wololo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wololo` DEFAULT CHARACTER SET utf8 ;
USE `wololo` ;

-- -----------------------------------------------------
-- Table `wololo`.`Elemento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wololo`.`Elemento` (
  `idElemento` INT NOT NULL AUTO_INCREMENT,
  `Id` VARCHAR(45) NULL,
  `Clase` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idElemento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wololo`.`Click`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wololo`.`Click` (
  `idClick` INT NOT NULL AUTO_INCREMENT,
  `idElemento` INT NOT NULL,
  `Fecha` DATETIME NOT NULL,
  PRIMARY KEY (`idClick`),
  INDEX `fk_click_elemento_idx` (`idElemento` ASC),
  CONSTRAINT `fk_click_elemento`
    FOREIGN KEY (`idElemento`)
    REFERENCES `wololo`.`Elemento` (`idElemento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
